一门语言是否能够长期流行，更语言的本身特性有一定的关联，关键是在于是否有一个基于它的杀手级应用(killer app)

ruby killer app - ruby on rails (这个应用很牛逼，但其核心很快就被 python js 等其他动态语言学了过去)

C killer app - unix (C语言是操作系统和硬件打交道的桥梁)

Java killer app - 一些中间件，能够很方便的做一些WebApp，积累了很多商业化的厂商和软件包

Python killer app - Numpy

数组是有维度的

一维数组 [1,2,3] vector 向量

二维数组 [[1,2,3], [4,5,6]] matrix 矩阵  有行和列(两行三列)

三维及以上数组  tensor 张量 超过两维很难有直观的表现

In [1]:
!pip install numpy

Could not build wheels for numpy, since package 'wheel' is not installed.
You should consider upgrading via the '/Users/han/.pyenv/versions/3.7.6/bin/python3.7 -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])

In [4]:
print(x)
print(x[0], x[1], x[2])
print(type(x))

[1. 2. 3.]
1.0 2.0 3.0
<class 'numpy.ndarray'>


In [7]:
print(np.ndim(x))
print(x.ndim)
print(x.shape)
print(x.shape[0])
print(x.dtype)

1
1
(3,)
3
float64


In [8]:
x1 = x.astype(np.float32)
print(x1)
print(x1.dtype)

[1. 2. 3.]
float32


In [10]:
x2 = np.array([1,2,3], dtype=np.float32)
print(x2)
print(x2.dtype)

[1. 2. 3.]
float32


In [11]:
y = np.array([2.0, 4.0, 6.0])

In [12]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [17]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
